/*
 * This source file was generated by the Gradle 'init' task
 */
package javaparser.test;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        // Replace These Fields
        String dirPath = "PATH/TO/PROJECT";
        String xlsxFile = "PATH/TO/SAVE/FILE/methods.xlsx";

        try (Workbook workbook = new XSSFWorkbook()) {
            Sheet sheet = workbook.createSheet("methods");

            AtomicInteger rowNum = new AtomicInteger(0);
            // Excel Sheet Header Row
            Row headerRow = sheet.createRow(rowNum.getAndIncrement());
            
            headerRow.createCell(0).setCellValue("File Path");
            headerRow.createCell(1).setCellValue("ClassName");
            headerRow.createCell(2).setCellValue("Step Definitions");
            headerRow.createCell(3).setCellValue("Methods");
            headerRow.createCell(4).setCellValue("Method Return Type");
            headerRow.createCell(5).setCellValue("Method Parameters");
            headerRow.createCell(6).setCellValue("Access Modifiers");
            for (int i = 0; i < 7; i++)
                sheet.autoSizeColumn(i);
                                    

            Files.walk(Paths.get(dirPath))
                    .filter(path -> path.toString().endsWith(".java"))
                    .forEach(path -> {
                        
                        // Parse each file
                        File file = new File(path.toString());
                        try {
                            CompilationUnit cu = StaticJavaParser.parse(file);
                            cu.findAll(MethodDeclaration.class).forEach(method -> {
                                try {
                                    
                                    // Parameters
                                    String parameters = method.getParameters()
                                            .stream()
                                            .map(param -> param.getType() + " " + param.getName())
                                            .collect(Collectors.joining("; "));
                                    
                                    // ClassName
                                    String className = method.findAncestor(ClassOrInterfaceDeclaration.class)
                                            .map(c -> c.getNameAsString())
                                            .orElse("");
                                    
                                    // SetpDefinitions or Annotations
                                    String stepDefinitions = method.getAnnotations()
                                            .stream()
                                            .map(annotation -> annotation.toString())
                                            .collect(Collectors.joining("; "));
                                    
                                    // Access Modifiers
                                    String accesModifiers = method.getAccessSpecifier().asString();
                                    
                                    // Excel Sheet Row
                                    Row detailsRow = sheet.createRow(rowNum.getAndIncrement());
                                    
                                    detailsRow.createCell(0).setCellValue(path.toString());
                                    detailsRow.createCell(1).setCellValue(className);
                                    detailsRow.createCell(2).setCellValue(stepDefinitions);
                                    detailsRow.createCell(3).setCellValue(method.getNameAsString());
                                    detailsRow.createCell(4).setCellValue(method.getType().toString());
                                    detailsRow.createCell(5).setCellValue(parameters);
                                    detailsRow.createCell(6).setCellValue(accesModifiers);
                                    for (int i = 0; i < 7; i++)
                                        sheet.autoSizeColumn(i); // Auto Resize Cell
                                } catch (Exception e) {
                                    System.out.println(e.toString());
                                }
                            });
                            System.out.println("----------------");
                        } catch (FileNotFoundException e) {
                            System.err.println("Error parsing: " + path);
                        }
                    });
            try (FileOutputStream fos = new FileOutputStream(xlsxFile)) {
                workbook.write(fos);
            }
        } 
    }
}
